[debug] [2024-06-12T18:51:19.085Z] ----------------------------------------------------------------------
[debug] [2024-06-12T18:51:19.093Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\sneisewander\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-06-12T18:51:19.094Z] CLI Version:   13.11.1
[debug] [2024-06-12T18:51:19.094Z] Platform:      win32
[debug] [2024-06-12T18:51:19.094Z] Node Version:  v20.14.0
[debug] [2024-06-12T18:51:19.094Z] Time:          Wed Jun 12 2024 13:51:19 GMT-0500 (Central Daylight Time)
[debug] [2024-06-12T18:51:19.094Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-06-12T18:51:19.150Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-06-12T18:51:19.151Z] > authorizing via signed-in user (sneisewander@raynor.com)
[debug] [2024-06-12T18:51:19.151Z] [iam] checking project family-reunion-2025 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-06-12T18:51:19.152Z] > refreshing access token with scopes: []
[debug] [2024-06-12T18:51:19.153Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-12T18:51:19.153Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-12T18:51:19.261Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------973057068115512651763302","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: self-signed certificate in certificate chain
[debug] [2024-06-12T18:51:19.262Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-06-12T18:51:19.262Z] > refreshing access token with scopes: []
[debug] [2024-06-12T18:51:19.263Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-12T18:51:19.263Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-12T18:51:19.319Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------028523049283617465451742","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: self-signed certificate in certificate chain
[debug] [2024-06-12T18:51:19.320Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
